---
editor_options:
  markdown:
    wrap: 72
---

<!-- rmarkdown::render_site(output_format = 'bookdown::pdf_book', encoding = 'UTF-8') -->

# Preferences and Economic Redistribution 

## Preference formation 

During the past decade, the research field of individual preferences toward economic redistribution constitute an interdisciplinary field in the social sciences [@alesina_preferences_2010;@steele_attitudes_2019]. In this regard, as a result of disciplinary boundaries, the phenomenon has been addressed through a range of concepts, such as _attitudes_ toward redistribution [@Garcia-Sanchez19], _social or welfare policy_ preferences [@breznau_economic_2010;@rehm_risk_2016] and _preferences, support or demand_ for redistribution [@steele_wealth_2022;@evans_strong_2018;@jaime-castillo_social_2019]. Across this body of literature, the common denominator is that individuals in society hold different views about what should be the role of government in taking measures for providing welfare and to what extent this role has to be accomplished. In order to establish boundaries and properly conceptualize this phenomenon, we need to review previous discussions in the literature. 

The theoretical framework proposed by @Janmaat2013 distinguishes between the concepts of perceptions, beliefs and judgments about economic inequality. First, perceptions refer to subjective descriptive estimations, in other words, how individuals think existing inequality is. Second, beliefs are understood as the normative dimension regarding how income distribution should be. Finally, judgments are considered as the normative evaluation of the existing inequality, referring to what extent it is considered good or desired [@Janmaat2013,p.4]. Within this framework, the concept of preference is occasionally misled with beliefs or judgments. In this regard, is relevant to point out that the ideas about how the object (e.g. inequality) should be, do not explicitly consider its' evaluation. In this line, the concept of preference needs to be distinguished from the previous framework, because the phenomenon studied in the redistributive preferences literature corresponds to the subjective appraisal regarding measures (e.g. social policies) to afront the existing levels of inequality. 

Another approach for the study preferences has been developed by @druckman_preference_2000. On their view, the formation of preferences can be understood as the combination of internal and external dynamics, suggesting that preferences derive from the evaluation of an external object and its' attributes relative to another (e.g. public policy). Objects can be observable physically continuous phenomena (e.g. furniture) and unobservable, physically discontinuous phenomena (e.g. shared ideas) [@druckman_preference_2000,p.4]. In addition, individuals evaluate based on beliefs toward the attributes of the object, which in turn depends on previous information which is directly linked to perception and previous experience [@druckman_preference_2000,p.5].      

Both approaches mentioned constitute an insightful understanding of what preferences are and how they are formed. Nevertheless, there is a difference that needs to be clarified. On the one hand, Janmaat's [-@Janmaat2013] approach allows distinguishing the descriptive from the normative dimension in the study of subjective inequality but is less clear toward the concept of preferences. In this regard, we do not posit that preferences do not have a normative component, but this framework is not enough to understand preference formation. On the other hand, @druckman_preference_2000 don not explicitly consider preferences to be linked with norms. They suggest that preferences are the function of beliefs, and the latter are systematically formed through perception and experience. In this regard, preferences correspond to the evaluation of an external object to be ranked by the observer based on actual beliefs. What we say is that both approaches share the assumption that the formation of preferences is not entirely neither internal nor external to the subjects. To be precise, a shared point is that perception is the basis for evaluations, that lead to the formation of preferences towards objects. 

The crucial point in which both approaches differ is how they define beliefs. In our view, for @Janmaat2013 beliefs are more static, in order that they correspond to the normative dimension, but for @druckman_preference_2000 due to beliefs being a function of perception and experiences they are more dynamic and susceptible to being updated by external shocks (e.g. information) [@druckman_preference_2000,p.6]. In this regard, preferences for redistribution can be understood as the individual's evaluation towards the role of government in managing the economic distribution on top of their actual perceptions and beliefs. Furthermore, preferences are influenced by the attributes of governmental actions that are represented by public policies. Hence, preferences can be addressed through the evaluation of government responsibility for the reduction of economic inequality globally, or by focusing on the characteristics of a concrete welfare policy.     

## Redistribution: what, how and who 

How the redistributive preferences literature has addressed the phenomena, apart from the previous distinction in preference formation, it is important to point out how preferences have been conceptualised across the literature. Previously, we have mentioned that disciplinary boundaries influenced the denomination of the phenomena. Despite this, this section presents **three** of the main conceptual approaches that have been empirically discussed across the literature. 

Preferences can be approached according to how concrete the attributes of the evaluated object are. One way to empirically addressed preferences for redistribution is the **reduction of economic inequality** which refers to what extent individuals believe that the government should be responsible for the reduction of the income gap between rich and poor, which has become one of the most common approaches for the study of preferences in the literature. For example, based on the General Social Survey @alesina_preferences_2010 analyse the evaluation of citizens about the role of government in Washington in improving the standard of living of all poor or if they should take care of themselves. From a cross-national approach, using data from the World Value Survey the @alesina_preferences_2010 analysed to what degree citizens believe that welfare should be the responsibility of individuals or that the government should provide universal support. On the same line, @Garcia-Sanchez19 scrutinise to what extent individuals agree that the government is responsible for reducing the differences between high and low incomes by employing the International Social Survey Programme. Looking at regional comparisons, @jaime-castillo_social_2019 examined European citizens' opinions on the idea that government should take measures to reduce income differences by employing the European Social Survey. Finally, @franetovic_preferences_2022 compared Latin American countries using the Latinobarometer survey, analysing to what extent subjects agree that government should implement policies to reduce income inequality between rich and poor. Overall, these cases briefly describe how the literature has empirically addressed general preferences for redistribution without addressing specific welfare policies.    

<!-- USA: “Some people think that the government in Washington should do everything to improve the standard of living of all poor Americans. Other people think it is not the government’s responsibility, and that each person should take care of himself”-->

<!-- WVS: ‘People should take more responsibility to provide for themselves (1) versus ‘The government should take more responsibility to ensure that everyone is provided for (10).”-->

<!-- ISSP: ‘It is the responsibility of the government to reduce differences in income between people with high incomes and those with low’ -->

<!-- ESS ‘the government should take measures to reduce differences in income levels’, with responses ranging from 1 (‘agree strongly’) to 5 (‘disagree strongly’). Possible responses are ‘Agree strongly’, ‘Agree’, ‘Neither agree nor disagree’, ‘Disagree’ and ‘Disagree strongly’. -->

<!-- LB: The State [corresponding country] should implement firm policies to reduce income inequality between rich and poor. To what extent do you agree or disagree with this statement?” This variable ranges from 1 (“strongly disagree”) to 7 (“strongly agree”).-->

Second, another body of literature has addressed preferences for redistribution based on the evaluation of certain **social policies** (e.g. unemployment benefits or health insurance). In this line, the individuals or groups that potentially become recipients of these welfare policies can be conceptually distinguished between those who are directly affected by policies in the short term (e.g. the poor or unemployed) [@Aaroe2014] and those who are going be affected by them, potentially or directly, in the future (e.g. ill or retired) [@castillo_deserving_2019;@rehm_risk_2016]. In this regard, how the government enacts welfare policies also considers the characteristics of the recipients of the benefits. This subject has been addressed by the deservingness heuristic approach, which adverts to what extent a certain group or individuals are considered to be within the scope of benefits of a certain welfare policy [@Jensen2017]. Therefore, it has been argued that public preferences toward redistributive social policies represent the evaluation of the policy, taking into account to what extent it affects the present (or future) material interest of the evaluator (e.g. income tax rise), but also the attributes of the recipients of the enacted policy [@garcia-sanchez_two_2022]

Finally, another dimension is how individuals rationalize the link between tax policy and economic inequality. In this regard, there is research that employed the concept of preferences for progressive taxation as a way to study redistributive preferences. The argument is that the link between income and welfare is increasingly relevant in societies with a progressive tax regime in which households on the top of the income distribution are those who contribute more and get directly benefited less by redistribution in which the core assumption that links income and redistributive preferences relies on what extent individuals prefer a progressive tax policy [@cansunar_who_2021,p.1]. However, empirical findings have shown that even the more affluent are more willing to support progressive taxation when they perceive that someone is richer than them [@cansunar_who_2021]. In addition, there is evidence that demonstrates that, even against their material interest, low-income individuals support regressive tax cuts as a result of their perceived own tax burden, but also due to a lack of political information [@bartels_homer_2005].


<!-- 
In this regard, For political psychologist 

"who receives what and why" 

A less discussed issue in the preferences literature is the empirical relationship between taxes and redistribution.

Another aspect is the specific object, in this case, policies that are being evaluated by the observator.

A theoretical relevant aspect of how to understand this phenomenon is to disentangle the underlying dimensions that comprise it.  

 -->
The literature on redistributive preferences has proposed different mechanisms for explaining the demand for redistribution. 

# Objective position and material factors

The literature has pointed out objectice position as one of the main drivers of preferences for redistribution. As an extension of the median voter theorem, the Meltzer & Richard model [@Meltzer81] proposed economic self-interest as an explanatory mechanism for redistributive preferences. The model proposes income as the representation of voters' material interests expressed by their preferences as the function of the distance from the income median, where those below it hold higher preferences for redistribution compared with those above. In other words, those close to the bottom are more benefited by redistribution and less affected by the tax burden increase, compared to those close to the top of the income distribution.  

## Income, wealth and future income

The negative influence of economic self-interest on redistributive preferences has been widely documented in the literature. Evidence from the United States [@alesina_preferences_2010], Europe [@dimick_models_2018] and Latin America [@franetovic_preferences_2022] has supported the predictions of the theory. However, despite evidence in favour of the self-interest hypothesis, recent studies have shown mixed evidence regarding the adverse preferences of high-income groups, but also the role of market income as the main driver of self-interest. For example, a recent study on urban Brazilian citizens found a positive influence of income on redistributive preferences [@garcia-sanchez_creencias_2022]. The authors suggest higher awareness regarding income inequality among rich and educated individuals in an unequal context like Brazil which makes them express altruistic views about inequality and support higher redistribution. Although cross-national comparisons have shown the expected negative association, also null and positive effects of income among different redistributive domains, demonstrating that adverse preferences among the rich are not consistent across societies [@steele_wealth_2022, pp.10-13]. In this regard, the authors point out wealth as an alternative and more stable source of self-interest than market income.

The role of wealth has been little discussed in the redistributive preferences literature. @steele_wealth_2020 argued that wealth can constitute a more comprehensive aspect for studying economic resources while it encompasses the totality of assets, which in turn can be subdivided into "housing wealth", representing ownership of a dwelling, as well as other types of property such as land or vehicles. In addition, there are financial assets, such as savings accounts or shares in the financial market, that can be understood as "financial wealth" [@steele_wealth_2020,p.2]. Using cross-national data from the International Social Survey (ISSP onwards), @steele_wealth_2020 found higher relative importance of financial wealth in contrast to housing wealth. The author argues in favour of disaggregating both sources of wealth suggesting financial assets are often easily translated to liquid, rather than housing wealth that is commonly linked to mortgages and does not provide a direct income source. Thus, in contrast with market income, both house and financial wealth have an independent positive but heterogeneous influence on redistributive preferences across countries. In a similar vein, @steele_wealth_2022 took a deeper look into the influence of both wealth dimensions demonstrating that financial wealth has a stronger association among Nordic societies, arguing that income inequality in these countries is one of the lowest in the globe, therefore wealth inequality could be salient than income when individuals express their preferences. It is argued that wealth is related to a "safety net" effect. In other words, it provides economic security in the form of inheritance for the next generation, but also a protecting them from economic shocks (e.g. unemployment) and enhances life chances [@steele_wealth_2022,p.4].

@rueda_who_2019 have argued that most material self-interest literature focused on market income, but the relative importance of income prospects has not been explored appropriately. In other words, the analysis of the self-interest mechanism should not be limited to a measure of present income, but also pay attention to life course events and their potential consequences on _future_ material conditions. Their argument relies on the Mincer earning function, where income returns are a function of human capital and experience in the labour market [@rueda_who_2019, p.42]. However, the proposed influence of future income relies on the assumption that individuals _know_ about the life cycle of people from their same educational group. Thus, knowledge about income prospects can negatively influence actual preferences for redistribution. First, they demonstrate that actual and expected income were not highly correlated, in favour of their expectation about the independency of the effect of both on redistributive preferences. Second, their analysis using European cross-sectional and panel survey data confirm the robust effect of future income undermines preferences for redistribution.

The contributions on the role of wealth and future income point out the importance of time-varying individual characteristics, but also turn our attention to long-term changes like intergenerational transmission of advantages and social mobility. In this vein, there is an important body of literature on the role of social mobility (actual or expected) on preferences for redistribution. In the following section, I will revise recent evidence in this respect.   

## Social mobility

How social mobility influences preferences for redistribution has been influenced by disciplinary boundaries in the social sciences. For example, sociologists have focused on intergenerational social mobility employing occupational class schemes to analyse individual changes in labour market positions compared with the previous generation [@Connelly2016;@Erikson1992], while economics has paid more attention to income mobility [@alesina_intergenerational_2018]. Research on the subjective dimension of social mobility has been also developed during the last years, focusing on the influence of perceived economic situation compared to previous generations [@mijs_belief_2022]. The redistributive preferences literature has conceived social mobility as a factor able to boost self-interest via two situational mechanisms. On the one side, experienced intergenerational upward (downward) mobility is associated with lower (higher) demand for redistributive measures. On the other side, it is expected that prospects of upward mobility in the future, or for future generations, undermine redistributive preferences.

Evidence from the United States has shown intergenerational occupational upward mobility increases redistributive preferences, compared with the null effect of educational mobility [@alesina_preferences_2010]. Similarly, evidence from European countries using diagonal reference models for social class mobility has shown lower preferences for redistribution for upward-mobile individuals [@jaime-castillo_social_2019]. In the same vein, a study of Latin American countries demonstrates educational upward mobility has a robust positive influence on preferences redistribution and privatization of public services [@gavira_social_2008]. Overall, cross-national and single-case studies have shown evidence in favour of the unique explanatory capacity of having experienced upward social mobility through education and occupational class. However, it has been illustrated by the literature on subjective inequality, that perception plays a crucial role in how individuals rationalise their origin and destination positions.  

Studies have demonstrated that higher subjective social mobility increases the willingness to justify the system [@Day2017] and boosts acceptance of economic inequality [@fehr_social_2020]. A cross-national study found evidence in favour of the positive link of occupational and educational mobility on perceived social mobility but also demonstrated that subjective mobility weakens the effect of objective mobility on higher wage inequality justification [@kelley_subjective_2008]. A recent study in five western societies has shown that Europeans are more pessimistic about social mobility than Americans, but also their experimental results demonstrate that manipulation of perceived income mobility with pessimistic information increases support for redistribution, mainly through equality of opportunities policies [@alesina_intergenerational_2018].

Current or perceived levels of social mobility in society can influence the expectations about mobility prospects. In this regard, @benabou_social_2001 have formalized the prospective upward mobility hypothesis (POUM) as an extension of the median voter model, where even those below the income median can develop adverse preferences toward redistribution assuming that progressive taxes can negatively affect them due to their expectations of achieve incomes above the median. Empirical evidence has demonstrated expectations about upward social mobility are associated with lower support for redistribution. For instance, using a sample of Italian students the experimental manipulation of mobility prospects increases the demand for redistribution, being more salient among middle and lower-income individuals [@Filippin2003]. Another study in Spain demonstrates that redistribute preferences decline among individuals with subjective income expectations above the median and higher perceived meritocracy [@Jaime-Castillo2008]. On another approach, among Latin American countries higher expectations about the next generation's educational achievement diminish support for redistribution [@gavira_social_2008]. Using expected subjective well-being as a proxy of future economic security, @fong_prospective_2006 demonstrates that well-being prospects decrease support for redistribution, but also discussed the negative influence of internal poverty attribution (e.g. laziness).   

## Risk and externalities

Redistributive preferences are not entirely guided by present or current individual situations. Therefore, expectations about potential negative outcomes in the future can influence support for redistribution, which has been addressed by the literature through the concept of risk exposure. The concept is commonly defined as the chances of experiencing shocks across the life course that can undermine economic security and welfare [@rehm_risk_2016]. Welfare state literature on the field has linked risk in two veins. One part of the literature has pointed out labour market outcomes focusing on individual unemployment risk [@rehm_risks_2009]. Another body of literature has focused on deservingness heuristics, pointing out that the risk of being affected by random events, such as sickness-based needs, could motivate higher demands for health or unemployment welfare [@Jensen&Nauman2016]. 

It has been demonstrated by the literature that unemployment status increases demand for redistribution and social insurance [@steele_wealth_2020;@alesina_preferences_2010]. In this line, the argument for studying risk from a labour market approach relies on potential outcomes, not current employment status, where the odds of losing the current market income can rise the demand for redistributive policies. Another dimension of the link of unemployment risk is to what extent can national redistribution compensate for the negative employment impacts of globalization on certain economic sectors, arguing that greater influence of international trade is associated with higher demand for redistribution [@rehm_risks_2009,p.6]. However, empirical evidence has shown only an increment in redistributive claims for higher occupational risk at the individual level, but null evidence in favour of the compensation effect by the economic sector [@rehm_risks_2009]. In a similar vein, @Svallfors2006 has argued that labour market position provides information about work conditions and wages. Thus, it has been shown that lower incomes and consequently higher labour market risk among the lower classes are associated with higher demand for redistribution [@Svallfors2006]. Furthermore, a recent study has claimed automation as another source of risk, demonstrating higher levels of support for redistribution among lower-skilled workers with higher automation rates [@hoorn_automatability_2022].   

Social insurance demand through health-related policies has been also linked with risk exposure. The argument is that random shocks across the life course can increase the demand for redistribution [@alesina_preferences_2010,p.18]. However, the support for specific policies is influenced by their content and affected target groups [@moene_inequality_2001]. For instance, a cross-national study has shown that higher incomes increase the demand for governmental responsibility on health welfare, also a higher willingness to pay taxes for improving the health care system, but a null association with higher social spending for preventive medical check-ups [@Azaretal2018]. Also, another research demonstrates a higher unemployment risk increases the willingness to pay taxes for universal healthcare in 28 countries [@Maldonadoetal2019]. In addition, it has been demonstrated welfare system can influence the link between unemployment risk and health policy preferences, where high levels of health system privatization lead to less demand for healthcare spending to be negatively influenced by unemployment risk [@zhu_policy_2015].    

The influence of income inequality on the demand for insurance is not entirely related to labour market outcomes. It has been discussed by the literature that insurance motivation can be triggered by concerns about the negative consequences of inequality. In this regard, altruism has been proposed as an explanatory mechanism that links inequality with redistributive preferences of the top income groups [@dimick_models_2018]. It has been argued that negative externalities of income inequality on social welfare can motivate normative-driven altruistic preferences from affluent individuals [@dimick_models_2018]. Altruism relies on both individual and social utility of social welfare as desirable, assuming concerns about inequality as the normative foundation of altruistic preferences by the rich. Evidence from European societies has confirmed the claims of the theory, demonstrating an increase in redistributive preferences among the rich in highly unequal contexts, in contrast with the rich in lower inequality contexts [@rueda_who_2019;@dimick_models_2018]. Additionally, a recent study has also found evidence in favour of the theory in Latin American countries [@franetovic_preferences_2022, p.15]. On the same line, derived from the altruistic model it has been argued that crime as a negative externality can increase insurance demands [@rueda_who_2019, p.86]. In this regard, higher concerns about crime can motivate altruistic behaviour from the rich for high public spending aiming to mitigate crime rates as negative externalities. In this regard, it has been demonstrated that higher fear of crime or being a victim of crime in the past increases redistributive preferences [@rueda_who_2019, p. 113]. Then, the evidence shows that higher preferences among the rich can be explained through concerns about crime in highly unequal contexts [@rueda_who_2019, p. 128] 

# Normative factors

## Norms and values

Social norms constitute a crucial factor for the study of social order and behaviour [@esser_integrative_2015], but also provide an interpretative frame for understanding social welfare institutions [@esping-andersen_three_1990]. The literature on redistributive preferences has addressed this domain as an independent source of motivation for individual preferences as an alternative approach to the material self-interest explanations. Inspired by the sociological theory of action, @esser_integrative_2015 suggest that the _homo economicus_ or utilitarian paradigm focused on opportunities, incentives and rational expectations focus the explanations of human behaviour in the self-interest mechanism. On the other hand, from the _homo sociologicus_ or normative paradigm, institutionalized rules of action are learned through socialization and internalization processes, therefore human behaviour will unconditionally be influenced by normative appraisals. A third proposed approach is the interpretative paradigm, which seeks to synthesise rational and normative approaches to develop a situational-dependent model of action based on frame selection [@esser_integrative_2015, p. 69-80]. Frames are ideal-typical situations based on previous experiences that can provide meaning to the evaluated situation, which can activate two possible modes: automatic-spontaneous (as) or reflecting-calculating (rc). The as-mode is strongly influenced by previous experience and choice selection is less reflexive. In contrast, the rc-mode takes into account several alternatives where uncertainty and future consequences activate moral evaluations. Thus, how action is guided by weighting utilitarian or normative evaluations can serve as an explanatory frame for variations in redistributive preferences.

The literature on preference for redistribution has addressed the influence of normative factors under the concept of _values_, but some research has used _beliefs_ or _ideology_ as interchangeable. However, political psychology and political science literature have suggested that values differ conceptual and empirically from the left-right continuum commonly used to study political ideology, arguing that egalitarian values can be shared by people placed on different points of the political spectrum [@feldman_understanding_2014]. The literature on social welfare preferences has discussed the role of egalitarian or humanitarian values as sources of normative motivations for redistribution. @feldman_humanitarian_2001 have that egalitarianism is related to the justice principle of equality and associated with higher support for government intervention in social and economic spheres, while humanitarianism is considered as a prosocial orientation close to the justice principle of need and commonly associated with poverty relief or health policies [@feldman_humanitarian_2001, p. 5]. 

Egalitarian values are expected to be associated with higher support for redistribution. For example, distributive justice literature has shown lower justification of economic inequality is associated with stronger egalitarianism [@Castillo2011;@Castillo2012b_multidimentional]. A study of six western industrialized societies demonstrated higher attachment to egalitarian values is strongly associated with support for government involvement in social services, price controls and basic needs subsidies [@breznau_economic_2010]. In a similar vein, a study on European countries shows that egalitarianism increases demand for progressive taxation and government social spending [@svallfors_government_2013]. Furthermore, evidence from European countries has shown a stronger association of egalitarianism with policy preference among higher-class individuals, arguing higher economic risk can weaken the link between abstract human values and redistribution [@Kulin2013]. Also, the relation of egalitarianism has been addressed in health policy preferences, where higher egalitarianism predicts higher support for public health provision and higher social spending on preventive health, but null support for progressive taxation for health policies [@Azaretal2018]. 

On the side of humanitarian values, evidence has shown among American citizens those that hold stronger humanitarian values tend to provide higher support for policies focused on elderly needs and poverty relief [@feldman_humanitarian_2001]. The authors argue that humanitarian values are not blind to social inequality, but rationalise social problems as part of the human condition. Regardless of the shared concerns about the justice of humanitarian and egalitarian approaches, the focus on needs by humanitarian values leads to support of specific policies rather than redistribution as a measure to accomplish the principle of equality. In this vein, a cross-national study of 28 countries has demonstrated a strong attachment to humanitarian values is associated with a higher willingness to pay taxes for providing universal health care, but also moderate the negative influence of risk exposure [@Maldonadoetal2019].

# Subjective factors

As a brief overview, drawing on the early work of @Kluegel-Smith1986, the interdisciplinary field known as *subjective inequality* has developed a wide body of literature on studying perceptions and preferences about economic inequality [@KluegelSmithWegener1995;@Janmaat2013]. In addition, the theoretical and empirical contributions from the sociological distributive justice research on status and justice evaluations [@jasso_justice_1978;@wegener_illusion_1987] still constitute an increasing research field on the causes and consequences of perceived economic inequality and social status [@castillo_perception_2022].

Regardless of the longstanding contributions of the subjective inequality and distributive justice fields, there is still a gap between this literature and the study of redistributive preferences [@Garcia-Sanchez19;@condon_economic_2020]. Recent efforts for reducing the stated knowledge gap, suggest further research on preferences for redistribution should go beyond the rational self-interest model and value-driven explanations, through the study of subjective social status and social comparison processes. Therefore, scrutinise their micro-macro foundations, dynamics and causal implications for redistributive preferences. 

## Subjective social status 

For the material self-interest model position within the income distribution is crucial for explaining preferences for redistribution. However, two propositions can be discussed. 1) individuals are *aware* of their income compared to others in society, and 2) their conclusion about the income of others is *accurate*. Therefore, there is no misperception. A fair body of research on subjective inequality has discussed these assumptions suggesting the claimed utilitarian motivation in the self-interest model could be confounded by perception.

The study of subjective views about status has been developed around the concept of subjective social status (SSS) understood as the perception of individuals about their place in the social hierarchy [@Evans2004]. It is possible to mention three relevant empirical, but also theoretical contributions. First, the "middle-class" perceptual bias is the persistent tendency of individuals to place themselves around the middle of the social hierarchy, showing variations regarding country levels of wealth and income inequality [@Lindemann2014]. Second, the moderate and inconsistent association with objective status measures like occupational class or education [@Castillo2013;@IturraMellado2019]. However, it has been shown that income has a robust positive influence in cross-national [@Lindemann2014] and longitudinal studies [@ChenWilliams2018]. Furthermore, a sample of older American individuals demonstrates the influence of personal net worth on increasing subjective status [@Andersson2018a]. A third contribution address the role of social comparison through the development of the reference group and reality blend hypothesis [@KelleyEvans1995] as an explanatory mechanism for the aforementioned findings. 

The reference groups and reality blend hypothesis (R&R-blend) was suggested as an explanatory mechanism of subjective social status [@KelleyEvans1995;@Evans2004], relying on two core assumptions. First, objective circumstances are represented by individuals' location on the social hierarchy, characterised by socioeconomic characteristics such as income or wealth, educational level, or occupation. In other words, these "material forces" can influence subjective status and class identification, but are not the only explanatory factors [@KelleyEvans1995]. On the other hand, it is suggested that socioeconomic status entails "social closure" generated by homophily, arguing that the socioeconomic composition within and between reference groups can influences perceived inequality [@Evans2004]. These circumstances contribute to the "subjective sampling" phenomenon, described as a type of availability heuristic through which perceive images of society are systematically biased [@Evans2017]. As a result, the joint forces of material conditions and the composition of reference lead individuals to misperceive the size of the bottom and top groups in society and to perceive themselves in the middle of the social hierarchy.

The social comparison theory [@festinger1954theory] suggests that individuals evaluate themselves in comparison to reference groups. Comparison can be performed across objective or subjective, like physical ability or opinions, but also about economic wealth or social prestige of individuals or groups. Previous contributions from social psychology on Equity Theory [@Adams1965] assume an exchange situation between individuals of similar characteristics, there is an expectation of proportionality of outcomes regarding inputs. Therefore, the justice evaluation will be a function of the equivalence of the input and output. Additionally, sociological contributions from the Relative Deprivation Theory [@Merton1968] highlight the role of perceptions about reference groups in the evaluation process. The inequality assumption regarding social status is crucial for the evaluation of the outcome of an exchange between two *asymmetric* actors. The distributive justice literature has suggested judgments about distributional outcomes are linked with previous perceptions of actual distribution [@Wegener1990]. Therefore, the social status of the observer can lead to illusionary distributional perceptions that consequently could bias distributional judgments [@Wegener1987].

## Social comparison and redistributive preferences

An essential component to link social comparison processes and preferences for redistribution relies on *who* are the target individuals or groups under comparison. The previous argument suggests that *Ego's* perceived social status is generated by social comparison processes, which can be theoretically explained by the mechanism described in the R&R-blend hypothesis. However, this approach assumes that social comparison *always* focuses on individuals with similar features from the nearest network but does not consider the contact with individuals or groups of different social status that could lead to variations in perceptual outcomes derived from an *asymmetric* social comparison. Thus, recent evidence in social psychology suggests that studying social comparison comprises three aspects that need to be considered: _direction_ (e.g., upward, downward), _target_ (e.g., friend, stranger), and _dimension_ (e.g., status, appearance) [@arigo_methods_2020] Therefore, an expectation is that individuals of low (high) subjective status experience more (less) relative deprivation [@Smith-eta2020_relative-deprivation]. Furthermore, it has been suggested that upward comparisons trigger negative judgments about economic distribution and feelings of deprivation that boost negative perceptions about economic inequality [@Jasso1990], decreasing life satisfaction and subjective well-being [@Olivos-etal2020]. In this regard, the literature that has directly addressed the role of social comparison and subjective social status on redistributive preference is scarce. However cross-sectional and experimental evidence have shown a wide of possibilities to address the link.

### Imagined economic others 

@condon_economic_2020 conducted an experimental study on American individuals to test the hypothesis that upward (downward) comparison should derive in more (less) demand higher government's responsibility to reduce income differences between the rich and poor. Nevertheless, they found that upward social comparison had a null effect on global redistribution, but increases the demand for social security, education, food, and unemployment insurance. They also demonstrate that the upward comparison causal effect is higher among middle-higher income groups, explaining that the "imagined" rich other is generally represented by individuals with incommensurable wealth and power.

### Perceived income distance 

Another study conducted by @cansunar_who_2021 employed cross-sectional data from the ISSP inequality module to test if overestimating the income of the rich as the reference group but also underestimating subjective status increases demand for progressive taxation. Drawing on an adaptation of the justice income evaluation function [@Jasso1999] the author operationalises the individual income distance to a CEO of a company as the high-status reference group. The results demonstrate that individuals that perceived themselves in the middle-class support higher progressive taxes. Similarly, high-income individuals support progressive taxation when they locate themselves on the top of the social hierarchy and believe others earn significantly more than them [@cansunar_who_2021, p. 7]. In other words, support for progressive taxation decreases as subjective status is lower and is higher when the perceived distance from the CEO increases. 

### Frequency of contact

A cross-national study of 22 countries employing data from the ISSP, @garcia-castro_perceived_2022 scrutinise the association of different perceived economic inequality measures on redistributive prefereces. Their results show a positive influence of both downward and upward experiences of social comparison operationalized through the following question: "How often do you have any contact with people who are a lot richer [poorer] than you when you are out and about". These results provide the possibility of understanding to what extent social comparison can be associated with other dimensions of perceived economic inequality. However, an open question is related to the hypothetical conditional effect of social comparison across income groups as was demonstrated by @condon_economic_2020. In other words, do social comparison experiences have the same influence on redistributive preferences for poor and rich individuals?

<!-- 
@andersson_occupational_2022
@Andersson2018a evidence from the United States
@Castillo2013 evidence from Chile
@ChenWilliams2018 and @chen_discordance_2015 evidence from China
@Evans2004 cross-national focuses on economic development
@IturraMellado2019 comparative of Latin American countries
@Lindemann2014 Europe cross-national, focus cross-level interaction of 
@ricci_perceived_2016 Europe and USA 
@Rubin2014a  -->

### Social networks and social comparison

The R&R hypothesis suggests a theoretical link between acquaintance social networks and subjective views about economic inequality. Thus, the role of network composition will be discussed as a source of social comparison. The assumption here is that the size and composition of social networks influence perceptions about income inequality.

A study by @kim_social_2021 demonstrate that a network with high-status individuals increases subjective social status in China and Taiwan, but has a null effect in Japan and Korea. 

Proposition 1: high socioeconomic diversity of the network will increase subjective social status.

<!-- @Olivos-etal2020
@kim_social_2021
@schulz_network-based_2022 -->

<!-- 
Para referencias del rol del estatus social subjetivo sobre actitudes revisar

* @brown-iannuzzi_privileged_2021
* @brown-iannuzzi_relationship_2017
* @brown-iannuzzi_subjective_2015

cómo elige compararse la gente en Europa?: 

* @gugushvili_which_2021
* @buchel_objective_2021 multinivel hibrido 

A less developed aspect is subjective inequality

* Preferences [@alesina_preferences_2010]. Este book chapter es una combinación literature review con evidencia de USA.
* Perception of economic inequality [@Garcia-Sanchez19]. 
* Reference group and Reality [@Evans1992;@Evans2004;@Evans2017]
* Welfarism, higher class fatigue [@evans_strong_2018] -->

# Contextual factors

(To be developed)

## Economic inequality

It is based on the subjective median-voter hypothesis [buchel_objective_2021]. The general assumption is that subjective status, compared to income, have a stronger negative impact on redistributive preferences (H1). As has been shown, economic inequality has a negative association with subjective social status (via increasing upward comparison). Therefore, the negative influence of subjective social status will be positively moderated by income inequality.

## Social distance and Spatial Segregation 

"inferences about the causes of inequality, people draw on lessons from past experience and information about the world, both of which are biased and limited by their background, social networks, and the environments they have been exposed to" [@mijs_inequality_2018]

<!-- How do we measure social distance? subjectively? objectively? Is this related with segregation?  

@mijs_america_2021 about the role of social segregation, institutions and mechanisms

@rueda_who_2019 (p. 118) argues that population density/urbanization can be a proxy of spatial segregation. They use the concept of "sorting" 

> Rodden, J. (2010). The geographic distribution of political preferences. Annual Review of Political Science 13(1), 321–340. -->







