---
editor_options:
  markdown:
    wrap: 72
bibliography: [P:/library-full.bib]   
biblio-style: apalike
---

<!-- rmarkdown::render_site(output_format = 'bookdown::pdf_book', encoding = 'UTF-8') -->

# Reference groups, personal networks, and perceived inequality 

## Reference groups and images about inequality

Building on the early work of @Smith1981, the study of economic inequality from a subjective approach has suggested that people's beliefs about economic affairs are stratified according to their position in the social hierarchy  [@KluegelSmithWegener1995;@Aalberg2003]. In addition, the sociological distributive justice literature has contributed to explaining how people form their judgments based on how their structural position, as well as by their perceptions of economic inequality and social status [@wegener_illusion_1987;@Jasso2001]. However, regardless of these contributions, there is still a gap knowledge gap between the formation of inequality perception and the study of redistributive preferences [@Garcia-Sanchez19;@condon_economic_2020]. For the material self-interest model [@meltzer_rational_1981], the position within the income distribution is crucial for explaining preferences for redistribution. Nevertheless, two propositions have been discussed in that regard. 1) individuals are *aware* of their income relative to others in society, and 2) their inference about the income of others is *accurate*. Recent research on perceived inequality has questioned these assumptions, suggesting that the claimed utilitarian motivation in the self-interest model could be confounded by the influence of reference groups on perception [@condon_economic_2020;@hvidberg_social_2020;@trump_income_2023;@becker_significant_2021]. Consequently, further research on redistributive preferences should go beyond the rational self-interest model and value-driven explanations by focusing on the influence of reference groups.

Social psychology and sociology have previously addressed the role of reference groups on perception. For example, social comparison theory suggests self-evaluation is driven by comparison with reference groups conceived as similar regarding physical ability or opinions, but also about economic wealth or social prestige [@festinger1954theory]. Likewise, Relative Deprivation Theory highlights the relevance of the perceived status of reference groups, where inequality is crucial when evaluating the outcome of an exchange between perceived asymmetrical actors [@Merton1968]. Moreover, the distributive justice literature has suggested that judgments about distributional outcomes are linked with previous perceptions of actual distribution [@Wegener1990]. It is argued that the observer's social status can lead to illusionary distributional perceptions that consequently could bias distributional judgments [@wegener_illusion_1987]. Hence, even if there is a relative consensus about the relevance of reference groups in social comparison and justice evaluations, little research has addressed the attributes of reference groups on perceived and preference inequality comprehensively.

@Evans1992 have proposed two dimensions to study the role of reference groups on perceived images of stratification and social status. First, one aspect is to consider income or wealth, educational level, or occupation as the individual socioeconomic basis that shapes economic inequality experiences. Therefore,  perceptions of economic inequality and status are partially explained by material conditions but do not explain the psychosocial processes involved with the images of social stratification [@Evans1992]. On the other hand, socioeconomic status entails social closure generated in personal networks homophily, arguing that the reference groups' socioeconomic composition influences images about stratification and social status via subjective sampling phenomenon, described as a type of availability heuristic that induce inaccurate perceptions [@Evans2004]. Therefore,  society is perceived according to the distribution of status positions in the surrounding social circles  [@Evans1992,p. 465]. For example, individuals in both high and low-status groups estimate the size of the lower and upper groups inaccurately, like a family doctor compared to a medical school professor, or a skilled worker compared to a garbage collector.  Therefore, the overestimation of reference groups' size strengthens 
the tendency to rank themselves in the middle of the social hierarchy. Additionally, as economic prosperity rise, socioeconomic status increases at the individual level, but also at the status of relatives, friends, or co-workers. Consequently,  people with higher subjective status reference groups do indeed perceive society as more egalitarian [@Evans2017, p. 33]

The study on subjective social status has contributed with three main remarks. First, it increases according to structural positions such as social class and education, particularly regarding wealth and income  [@Lindemann2014;@ChenWilliams2018;@Andersson2018a:@Castillo2013;@IturraMellado2019;@andersson_occupational_2022]. Second, the subjective middle-class tendency is persistent across countries, where economic prosperity increases subjective status, while economic inequality diminishes it [@Lindemann2014]. Third, the combined influence of structural positions and reference groups in personal networks is conceptualised as the Reference Group and Reality (R&R) blend hypothesis [@KelleyEvans1995 ]. It suggests that the joint forces of economic growth, economic inequality, and reference group homophily shape perceived economic inequality. These images have an anchor effect on how individuals perceive themselves in the social hierarchy as well. For example, if society is perceived as egalitarian, people perceive their network and themselves in higher structural positions, and vice versa [@Evans2017]. 

Given that interactions are not limited to the closest personal networks, it is reasonable to consider family and friends as the most significant ties but not the unique information source about economic inequality.  Therefore, It is argued that the link between income inequality and preferences for redistribution should consider (1) how comparisons with reference groups are performed,  (2) their attributes within personal networks, and (3) to what extent experiencing socioeconomic diversity is associated to perceived economic inequality, which consequently operates as an explanatory mechanism of redistributive preferences.    

## Comparison and reference groups

Addressing the relevance of reference groups implies considering *who* are the target groups. Previously, it was suggested that the homophilic tendency of social ties formation influence perceived economic inequality. However, it is assumed that comparison focuses on individuals with similar attributes from the closest network, not specifying if this mechanism applies to diverse groups, implying that asymmetric comparison could lead to different outcomes. Consequently, analysing the role of reference groups in comparison processes should consider three dimensions: _direction_ (e.g., upward, downward), _target_ (e.g., friend, stranger), and _dimension_ (e.g., status, appearance) [@arigo_methods_2020]. For example, comparisons with a high-status reference group are expected to lead to higher relative deprivation [@Smith-eta2020_relative-deprivation]. Furthermore, upward rather than downward comparison can trigger experiences of relative deprivation and increase perceived economic inequality [@Jasso1990] and undermine life satisfaction [@schneider_why_2019]. Consequently, identifying the relevance and attributes of reference groups has yet to be clarified when addressing their influence on perceived and preferred economic inequality.

Studies have addressed how certain groups are preferred for evaluating economic conditions. For example, @clark_who_2010 examined the intensity and direction of income comparisons, finding that the greater the importance attributed to income comparison, the higher the chances of declaring work colleagues as the preferred reference group, followed by family and family friends. Furthermore, those in less risky labour market positions are less likely to compare, while almost all employees are likelier to compare with work colleagues than family or friends. Another study scrutinised the preferred reference groups for economic comparisons, showing that friends and neighbours are the most prevalent choice [@gugushvili_which_2021, p. 12]. Additionally, being active in the labour market in urban areas increases comparison preference with those groups, while highly educated and Downard mobile individuals prefer their family of origin as a reference group. However, the reference groups provided in the study are limited, excluding other relevant groups such as co-workers in economic comparisons [@clark_who_2010].  

Research on the influence of asymmetric reference groups on perceived inequality and preferences for redistribution has gained increasing attention recently. @clark_who_2010 found that individuals who prioritize social comparisons and choose family members as their reference group tend to demand higher levels of redistribution. Similarly, @cansunar_who_2021 reported that high-income individuals tend to support progressive taxation when they perceive themselves as occupying the highest rungs of the social hierarchy but also believe that others earn substantially more than them. Also, @garcia-castro_perceived_2022 showed that frequent interaction with individuals considered "much richer (poorer)" has a positive effect on redistributive preferences when the reference group is deemed poorer, but no effect when it is considered richer. Experimental research has also provided supportive evidence. For example, @brown-iannuzzi_subjective_2015 conducted a study on an online sample of American participants and found that redistributive preferences are likely to increase when individuals make upward social comparisons and perceive themselves to be worse than average in economic terms. Meanwhile, @Condon2020 analyzed a representative sample of American adults and discovered that upward social comparison diminishes subjective social status, but has no significant impact on general redistributive preferences. Instead, it increases demands for specific policies, such as poverty relief and unemployment insurance. Additionally, the upward comparison effect is more pronounced among upper-income individuals, suggesting that they imagine the advantaged others as individuals with outstanding amounts of wealth and power [@condon_economic_2020, pp. 80 - 100]. 

The aforementioned observational and experimental evidence offers valuable insights into the social psychological mechanisms that link reference groups and redistributive preferences. However, an important consideration is how these interactions occur in everyday life, given that social, economic, and institutional factors often segregate individuals and groups [@mijs_is_2021]. An assumption in this regard is that nuances in social interactions with reference groups, such as their intensity and direction, provide a framework for inferring how economic resources are distributed in society. Yet, limitations of the reference group approach exist, such as (1) the difficulty of identifying specific groups relevant to an individual, (2) the challenge of describing groups in terms of socioeconomic or demographic characteristics, and (3) the ambiguity of their relevance to the individual. 

@Evans2017 suggested that the homophilic nature of personal networks could serve as an inferential framework for inequality perceptions in general, and redistributive preferences in particular. 

Empirical research has partially supported their theoretical claims about the importance of family, friends, neighbours, and coworkers as relevant reference groups [@gugushvili_which_2021; @clark_who_2010]. 


## Perceived inequality and redistributive preferences
<!-- perceived inequality and preferences -->

The debate concerning the role of economic inequality in increasing the demand for redistribution established by the self-interest approach through the median voter hypothesis has received partial empirical support, being consistent when addressing between-country differences but absent in within-country variations on income inequality [@franetovic_preferences_2022;@Schmidt-Catran2016]. Notwithstanding, an ongoing debate around an alternative mechanism that might explain the connection of economic inequality with redistributive preferences has focused on the socio-psychological processes involved in forming subjective appraisals of economic inequality and social status [@castillo_perception_2022]. Empirical efforts have been quite robust in establishing that among the different conceptualisations of perceived economic inequality, demand for redistribution increases when people perceive that economic inequality is higher [@evans_strong_2018;@Bobzien2019;@Garcia-Sanchez19;@garcia-castro_perceived_2022;@garcia-sanchez_creencias_2022]. A recent study by @trump_income_2023 has simultaneously discussed two crucial aspects of the claims of @meltzer_rational_1981 employing comparative survey data. First, she demonstrates that actual income inequality is not linked to perceived inequality (as salary gaps). Second, preferences for inequality and redistribution are associated with perceived inequality. Third, income inequality is not associated with either redistributive or inequality preferences. Hence, these results align with the idea that the comparison process between perceived inequality and desired (lower) economic inequality is what theoretically increases demand for redistribution [@trump_income_2023].  

Part of the literature has argued that the divided results regarding the link between current inequality and demand for redistribution might be related to the lack of information about the distribution of economic resources in society leading people to misperceive economic inequality [@Osberg2006;@Kelley1993]. However, the argument can be discussed in two aspects. First, survey instruments can cognitively challenge respondents when addressing quantiles, distributions, or numeric representations, such as wage inequality in contrast to graphical representations, which can lead to substantial differences in the size of the claimed misperception [@hadavand_misperceptions_2018, p. 249]. Second, even when experimental studies have shown that providing accurate information about economic inequality can influence perceptions that align preferences with self-interest [see @stantcheva_perceptions_2021;@hvidberg_social_2020;@mccall_exposure_2017;@karadja_richer_2017], the question of how this mechanism operates in everyday life social environments has yet to be further investigated. 

Thus to summarise, given that an individual's experience and information about society are often limited by their personal networks composed of family, friends, and acquaintances [@mijs_inequality_2018], a first implication is to focus on describing and analysing these attributes as a subsequent analytical step for understanding their consequences on perceptual and attitudinal outcomes. Therefore, echoing Evans & Kelley [-@Evans1992;-@KelleyEvans1995;-@Evans2004] original claims about the influence of homophily on perceived economic inequality and subjective status, recent research has focused on social networks as a way of describing social environments and assessing their consequences for perceived and preferred economic inequality. It is worth mentioning that the R&R blend hypothesis relies on the concept of *homophily* of reference groups for developing their argument without directly referring to the longstanding literature on social networks [@mcpherson_birds_2001]. Notwithstanding, recent research has adopted a network analysis approach for studying the influence of network composition and social capital on perceptual and attitudinal outcomes. Since both bodies of literature have little dialogue, analysing redistributive preferences from a social network approach constitutes a comprehensive way of understanding the link between social networks, perceived inequality and economic preferences. 

# Structure of association and social networks  

## Positions, association and tie formation
<!-- **Paragraph: homophily and network composition** -->
The study of personal networks requires describing the social structure as the basis for association patterns among individuals. The influential work of Peter @blau_inequality_1977 suggested that examining the nexus between people's positions and social relations implies paying attention to social differentiation, understood as the distribution of social position across the population. These positions are determined by hierarchical status and group membership, representing two forms of differentiation: inequality and heterogeneity. However, the foundations of social structure analysis count on the observable patterns of social association between these positions. The claimed emphasis on social processes of differentiation is rooted in how they shape interpersonal relations in the social structure, often conceptualised as relational networks [@blau_inequality_1977]. Given the distribution and intersection of nominal (groups) and graduated (status) parameters, such as religious diversity or income distribution, the substantive focus is on how society's structural conditions shape social barriers providing opportunities for contact and association [@blau_macrosociological_1977, p. 51]. The strength of the intersection between parameters reveals the degree of consolidation, for example, the correlation of graduated parameters such as education and income and their intersection with ethnicity as a nominal parameter. Consequently, consolidation influences social integration in order that intervenes in the chances of interaction between persons from diverse groups and statuses [@blau_macrosociological_1977, p. 33]. 

Structural and individual conditions that allow associativity are at the core of social network analysis. One of the most significant findings in the field is homophily, understood as the observed tendency of higher frequency of contact and tie formation between individuals of similar characteristics [@mcpherson_birds_2001]. These associations are structurally differentiated, tending to be segregated by hierarchical status and group membership (*status homophily*), such as education, gender, age, religious affiliation [@bargsted_pautas_2020], social class [@wright_relative_1992a] or ethnicity [@plaza_juntos_2022]. Furthermore, sociopsychological factors affect homophilic association as well, where behaviour and individual preferences tend to reinforce in-group dynamics (*value homophily*), isolating individuals from others' worldviews and opinions [@visser_attitudes_2004;@diprete_segregation_2011]. However, it is assumed that the influence of these factors strongly depends on the dynamic provided by structural constraints, such as group size and diversity [@blau_inequality_1977]. Thus, it is expected that both contact opportunities and association preferences contribute to establishing relatively isolated social environments [@mcpherson_network_2019]. Furthermore, this homophilic tendency generates that resources, information and behaviour tend to be segregated, implying that network structure introduces a certain degree of social distance, establishing boundaries among people's social worlds [@mcpherson_birds_2001]. 
  
Associativity depends on people's similarities, but intergroup contact in everyday social activities makes meeting opportunities possible. According to @feld_focused_1981, the _foci_ can be a social, psychological or physical entity around which joint activities are organised (e.g. places, persons, families, voluntary organisations). Therefore, when people participate in activities around the same focus, they tend to be interpersonally tied and form a dense cluster group. The focused organisation of social activities is considered more determinant than individual similarities. For example, even if two individuals are similar in their characteristics, the absence of a _foci_ and the joint activities around it will decrease their chances of association. This approach is critical of Homan's group balance theory [@homans_human_1951], which proposes that attitudinal and value similarities foster association, paying less attention to status or group membership similarities on tie formation around a _foci_. Notwithstanding, the focus theory recognises the relevance of the psychological dimension. Still, it suggests that organised activity spaces constitute a dominant source of ties and represent a significant aspect of people's social environments.

The strength of ties depends on the nature of the association. As focus theory suggests [@feld_focused_1981], the multiplexity of social positions implies that certain activity spaces matter most in forming social ties   [@blau_macrosociological_1977]. For example, the size of friendship networks tends to decrease through the transition to adulthood, while kinship ties such as the family of origin or partner choices tend to be more stable [@volker_social_2020;@gugushvili_which_2021]. Additionally, considering that intergroup associativity is influenced by the degree of social differentiation, certain social ties that cross boundaries are prompt to dissolution in the absence of spaces that integrate people around a _foci_, such as voluntary organizations, schools or workplaces [@mcpherson_birds_2001;@kossinets_origins_2009]. Hence, given that social integration entails the degree of intergroup relations through personal ties of association, network segregation reflects the social distance between groups and the availability of social resources embedded in social networks. 

## Social networks and resources

Social capital scholars have provided insightful contributions to studying resource inequality through social networks [@lin_building_2001]. This approach suggests that a person's social environment can be studied through ego-centred networks in which the dyads between a person (*ego*) and their contacts (*alteri*) represent the tie that provides access to resources, arguing that it is possible to characterise the access to valued resources like wealth, status or power through social ties, which provide researchers with an image of how stratified social environments are according to personal and social resources embedded in the ego's social network [@lin_access_1986]. From this perspective, personal resources are those possessed by an individual that can be used and disposed of freely without much concern for compensation. On the other hand, social resources are temporary and borrowed resources that can be accessed through one's direct and indirect ties [@lin_social_1999]. 

<!-- “human capital (education, experiences), initial positions (parental or prior job statuses), and egoís social ties (e.g., extensity of ties) are hypothesized to determine the extent of resources ego can access through such connections (network resources).” [Lin, 1999, p. 471] operational definition of network resources

“network resources, education, and initial positions are expected to affect attained statuses such as occupational status, authority positions, sectors, or earnings.” [Lin, 1999, p. 471] -->

<!-- instrumental and expressive outcomes -->    
According to social capital theory, the mobilisation of resources embedded in social networks is conceptualised in two types of outcomes: instrumental and expressive actions [@lin_building_2001]. Instrumental actions are described as the expected returns because of access to resources through social ties, such as the influence of acquaintances on the status attainment process [@Granovetter1973;@contreras_inequality_2019]. It has been suggested that instrumental actions take the form of three types of possible returns: economic, political, and social [@lin_building_2001]. It is argued that these three added social capital forms are objects of exchange processes. For example, increasing occupational status can be the key feature of higher authority positions in the workplace, representing increased control and influence as a political outcome. In addition, these positions can increase social recognition when considered legitimate, boosting trust towards ego within the network [@diprete_segregation_2011]. Among the possible explanations, three key processes have been described: information, influence and social credentials [@lin_building_2001]. For instance, certain strategic locations in the labour market (e.g. managers) provide meaningful information about job opportunities that could only exist with the tie. Additionally, authority and power positions imply influence on organisational decisions, like collaboration or member inclusion. Moreover, social credentials are attractive for organisations interested in the contacts held by certain positions, which incentivises organisational consolidation. 

Expressive outcomes are described as actions in which the expected return is social capital protection and consolidation to avoid any losses toward preserving current embedded resources and guarantee access to them [@vandergaag_position_2008]. The motivation for mobilisation to preserve pooled social resources comprises the broad network members, integrating ego's and alter's interests. In this line, the theory points out three main expressive returns: physical health, mental health and life satisfaction. Expressive actions aim to maintain the primary material and social resources to ensure protection and support against any threat that might harm physical or mental integrity and maintain optimism and satisfaction among family, work and community spheres [@lin_inequality_2000]. Both expressive and instrumental actions are not univocally independent and can reinforce each other. For example, physical and mental health is the basis for sustainable job performance or pursuing organisational leadership responsibilities [@lin_building_2001]. 

<!-- Explain name and position generator -->
<!-- Methodologically speaking, among the ego-centred network sampling techniques, the position and name generators represent the most used instrument for measuring positions of social contacts. The position generator is a standard method to assess an individual's access to different types of resources located in social positions [@lin_theory_2008]. This technique was first proposed by @lin_access_1986 and employs a sample of structural positions representative of resources highly valued collectively, such as occupations, authority, work units, class, or sector [@lin_social_1999]. Along with the list of positions, a set of questions can be included to describe the relationship between ego and alter, such as if they are friends, family or acquaintances. The position generator has been demonstrated to be a reliable method for capturing ego-centred networks. Still, a trade-off related to the data quality and the number of positions included should be made, where it has been suggested to include questions of at least 15 to 20 occupations [@vandergaag_position_2008]. On the other hand, the focus on labour market active groups has the disadvantage of excluding retired persons or students from the scope. Additionally, given the extensivity of the instrument, questions about each position are not included for the sake of parsimony, which is translated into a lack of detailed description about each tie. However, the hierarchical status nature of the data obtained provides sufficient information to describe the composition (average resources), heterogeneity (resource diversity) and upper reachability of resources (highest resources accessed) embedded in the ego's network, which entails one of the strengths of the position generator [@lin_building_2001].  

Another widely used instrument is the name generator/interpreter. It follows the same rationale as the position generator but fulfils some disadvantages, providing detailed information about specific contacts to which respondents feel closest or discussing personal and relevant matters [@vandergaag_position_2008]. After selecting connections, respondents fill in the name interpreter, which includes questions such as age, gender, education, occupation, and ethnicity, among others, and in some cases, the respondent can describe possible connections between their close ties, allowing them to richly describe ego's access to social positions and resources [@lin_theory_2008]. However, given that the instrument describes around 3 or 5 closer relationships, it is well established that these types of connections tend to be influenced by homophily which is translated into less diverse networks. However, rather than providing access to a wide range of positions (hence resources), close ties are related to friendship and kinship, which are more likely to perform a central role in expressive actions [@lin_building_2001]. An important remark is that both name and position generators can be employed in a complementary way. However, the name generator is more suitable for studying phenomena associated with the ego's close ties, such as patterns of friendship and kinship. In contrast, the position generator provides information about the ego's extended networks that are often more heterogeneous, including more diverse types of relationships and resources that can include acquaintances that provide access to different types of resources [@vandergaag_position_2008].   -->

<!-- evidence on access to social capital -->

## Class-based inequality in social networks

Recent literature has turned attention to the generative processes of social capital formation [@volker_social_2020], focusing on access to social capital through structural processes such as intergenerational social mobility and class inequalities. As the social capital theory claims, contact opportunities and association preferences are socioeconomically stratified [@lin_theory_2008]. Therefore, it has been demonstrated that access to diverse and higher resources through social ties follows a pattern of capital accumulation that reproduces preexisting inequalities, where class positions have been particularly salient for understanding habits of association that describe exclusion and segregation mechanisms observed through social ties along the class structure.

According to Weber [-@weber_economy_1978], classes are a common basis for action, defined by the position in the labour market and the access to specific opportunities and goods that come with this standing. In addition, the degree of intergenerational exchange leads to the development of social classes, characterised by particular socialisation patterns and lifestyles that are reproduced over time. The class situation is expressed through sociability practices, marriages, friendships, and social relations between people that belong to a particular status group. Similarly, the formation of classes has been described by @goldthorpe_sobre_1992 via two processes. First is demographic identity, where they become identifiable as collectivities by the continuity in which individuals and families retain their class positions across generations. Second is cultural identity, expressed in class members' distinctive shared lifestyles along with their preferred patterns of association. As Bourdieu [-@bourdieu_distinction_1984] suggests in his class *habitus* analysis, cultural capital is the pivotal attribute of these distinctive practices, represented by holding diverse cultural resources among the most salient are educational credentials [@bourdieu_distinction_1984]. Hence, this approach suggests that the socialisation of common lifestyles and shared worldviews facilitate the consolidation of classes, which is particularly salient among the upper classes that can choose socially segregated environments that increase their chances of meeting and establishing ties with similar others, therefore maintaining their privileged social positions by excluding others [@bourdieu_reproduccion_1981]. Jointly, these processes further reinforce the social distinctions between classes and contribute to the persistence of class structures. 

Class-based studies on social tie formation have shown that class permeability in friendship formation is strongly affected by property-based boundaries, in which owners are less likely to connect to the working class through friendship ties. By contrast, routine interactions between supervisors and workers might explain why the authority dimension is highly permeable [@wright_relative_1992a]. Similarly, the upper-middle class held less diverse networks in contrast to the intermediate class regarding their extended networks, while friendship network diversity increased for those who experienced upward mobility [@cepic_how_2020]. However, the gain in higher-status contacts associated with social mobility is moderated by family background, where upwardly mobile individuals are not able to equalise their social capital compared to the intergenerational stable [@carrascosa_class_2023]. Moreover, the *u-shape* distribution of ties between the two extremes of the class structure depicts the higher permeability of intermediate classes, where lower class-based homogeneity contrasts with the higher exclusion of the working poor and the self-selected higher status and lower diversity of contacts held by the upper-middle class [@otero_open_2021]. Additionally, the upper class is persistently engaged in formal organisations that increase their chances of bridging with diverse people in terms of skills and resources, in contrast to the homogenous pattern of civic engagement held by the working class [@pichler_social_2009]. The tendency to accumulate resources through social ties is intersected by individual characteristics as well, where the less educated tend to lose contact in contrast to the highly educated, while men gain in terms of high-status contacts compared to women [@volker_social_2020]. 

<!-- 
“Both the degree of homogeneity of a certain attribute X, and the degree of consolidation of attribute X with occupational position are contingent quantities that fluctuate over time and space. Thus, although network homogeneity along various dimensions has been well established, the degree of homogeneity is not a constant, and this is also true for consolidation.” ([Tubergen and Volker, 2015, p. 524](zotero://select/library/items/SX5YB8HQ)) ([pdf](zotero://open-pdf/library/items/D7BF9MID?page=4&annotation=U6PIX977)) IMPORTANTE

That can strengthen or challenge previous information, therefore modifying perception and also motivating shifts in preferences. Another possibility is that these experiences can increase our previous views, by confirming them [@visser_attitudes_2004]

- “Similarly, attitudes held by members of a person’s social network have been shown to predict changes in his or her attitudes over time, again consistent with social influence processes” [Visser and Mirabile, 2004, p. 780]

- “people’s political attitudes are socially structured, reflecting not only their own thoughts and feelings but the preferences of important others as well” [Visser and Mirabile, 2004, p. 780] 

- “several hypotheses about the impact of social network composition on individual-level attitude strength can be derived from existing social psychological theory and findings, and different theoretical frameworks imply a number of distinct psychological mechanisms through which social network composition may exert its effects” [Visser and Mirabile, 2004, p. 780]

- “Attitudes held with certainty are more durable than those held with less certainty (e.g., Gross, Holtz, & Miller, 1995). Thus, social network heterogeneity may decrease individual-level attitude strength by reducing the confidence that people have in the correctness of their attitudes” [Visser and Mirabile, 2004, p. 780]

Political homophily 
https://www.sciencedirect.com/science/article/pii/S0378873321001088#fig0005 

Early Adolescents Demonstrate Peer-Network Homophily in Political Attitudes and Values 
https://pubmed.ncbi.nlm.nih.gov/35613458/ 
 -->

## The role of macro-social conditions            

<!-- As presented above, the body of research has addressed the influence of social networks on perceived and preferred inequality it is far from being extensive at the individual level. On the one hand, few studies have systematically addressed the role of macro social conditions on social network structure [see @otero_lives_2022a]. On the other hand,  the influence of macro conditions like income inequality and economic prosperity have been discussed at the core of the redistributive preferences literature [see @Schmidt-Catran2016]. Consequently, this section aims to provide some exploratory insights regarding the extent to which macrosocial structures affect social interactions and network structure, as well as how the social distance nurtured by social segregation between individuals and groups could influence preferences toward economic inequality.   -->

As the social capital theory suggests, access to certain positions in the social structure is influenced by status position, as well as by individual preferences of association [@lin_access_1986].  Consequently, studies on the macro social conditions that influence access to social capital have distinguished between conditions in the (i) political, (ii) normative, and (iii) economic domains [@vanoorschot_social_2005;@son_social_2012;@pichler_social_2009]. Therefore, it is argued that these macro social conditions can bolster or hinder meeting opportunities, which in turn stratify the diversity and prestige of the accessed social positions,  that in the long run shape the conditions for the reproduction of social capital inequalities [@lin_inequality_2000].  

Regarding the political dimension, it has been argued that political institutions and regimes can influence the sociability structure of a society. This means that institutions, such as the political system establish to what extent citizens can participate in the public sphere [@son_social_2012].  For example, in democratic regimes in which civil rights are developed, social services and living standards tend to improve, as well as participation in voluntary organizations.  Evidence in this regard has not been conclusive, suggesting that social spending might increase social capital through the number of contacts [@scheepers_welfare_2002], but not regarding their prestige [@otero_lives_2022a, p. 115].  Additionally, it has been suggested that welfare policies might reduce life uncertainty. In industrialised capitalist societies, there are variations in terms of market dependency and the universality of benefits, in which social democrat or liberal regimes constitute different degrees of welfare generosity [@esping-andersen_three_1990]. Consequently, it is expected that in societies in which the political culture emphasises solidarity and egalitarianism, such as the social democrat regime does, social spending could equalise opportunities and improve overall life chances. Whereas, in liberal regimes market dependency is higher and social benefits are not extensive.  The evidence has shown that in social democratic regimes and higher social expenditure is associated with an increase in contact frequency,  prestige, and diversity [@visser_crowding_2018;@otero_lives_2022a].

Cultural orientations understood as the social norms that structure sociability establishing rules regarding how certain status positions are less attractive or needed have been taken into account as a structuring macro-social factor for accessing social capital.  @son_social_2012 suggests that cases like China and Taiwan, in contrast to the United States, crystalise two ideal-typical cultural orientations. In these societies, the macro institutional arrangement in capitalist and socialist political economies, as well as Western and Confucian cultural traditions have consequences in how social capital is accessed and mobilised. In this regard, for the study of the relational distance between people, he introduces three layers of social relations that work as recipients of social resources: *binding* (family-oriented ties), *bonding* (daily contact), and *belonging* (participation in formal organizations). On the one hand, East Asian societies are described as _collectivist_ according to the Confucian tradition that follows family-oriented sociability, in which _binding_ ties are crucial for having access to social resources [see @kim_social_2021]. On the other hand, Western societies are characterised as *individualistic*, in which the orientation of being associated with others through organisations motivates individuals to develop extended networks outside of the inner circle that may improve life chances,  providing greater relevance to the *belonging* dimension as a source of social resources [see @huang_subjective_2021]. In this regard, cross-national evidence has shown that individualistic orientations are associated with more prestigious positions, but not with contact diversity [@otero_lives_2022a, p. 116], suggesting that openness of individualistic lifestyles tends to be oriented towards status-seeking rather than appreciation of diversity. 

Economic inequality deserves special attention as a macro-social characteristic of societies. As previously reviewed, inequality in access to social positions and resources is strongly stratified. Additionally, the access and accumulation of social resources, particularly by the upper classes could be exacerbated by higher economic inequality. In other words, the rich become wealthier and the poor maintain their living conditions or worsen. Therefore, income inequality can strengthen current disparities in access to social resources between classes, increasing the chances of the upper classes to engage in voluntary associations and decreasing it for the working classes [@pichler_social_2009]. Additionally, it has been shown that inequality in access to prestigious contacts is less pronounced in unequal societies, while it increases the gap in terms of contact diversity, suggesting that income inequality increases the difficulties to meet and establish relationships with the higher class [@otero_lives_2022a]. In this regard, it has been shown that in an unequal context, the upper class is segregated in high-status social circles, increasing social distance and disconnection  [@carrascosa_class_2023;@otero_lives_2022].  

Scaling down the scope from the global or societal level, networks and associations can be also affected by local settings such as neighbourhoods or communities, which can differentially influence social relations in terms of frequency of contact, density and diversity of networks  [@lin_building_2001;@lin_inequality_2000]. Related research has demonstrated that spatial inequalities, such as urban segregation and residential choices reflect economic inequality in a local dimension, showing that distance is not only social or subjective, it is physical as well, where the upper classes are self-segregated tending to inhabit privileged and isolated neighbourhood, in which can develop their life project avoiding interaction with lower classes, reinforcing their privileged positions [see @mendez_upper_2019;@otero_space_2022]. 


# Social networks, perceived and preferred inequality    

## Social segregation and inequality perceptions

<!-- segregation-distance and perception  -->
The social network perspective offers an analytical approach from a meso-level perspective that allows linking the macro and micro levels of analysis to study social perception and behaviour [@hedstrom_causal_2010]. Therefore, networks allow studying social ties that bridge social groups through activities, friendship or family ties [@pichler_social_2009]. However, only some studies have addressed the claimed influence of social environments on how people perceive the magnitude of economic inequality. Consequently, a guiding assumption is that people's awareness of the amount and diversity of resources in their social network is associated with their degree of embeddedness in social relationships that provide significant benefits, such as better information and life chances, as well as the lack of them, that in ultimately shapes their perceptions of inequality [@Granovetter1973;@lin_building_2001].

How people perform inferences about the social world is linked to the degree of segregation in their immediate social environment, which determines the intensity and character of the information that ultimately shapes inequality perception [@mijs_is_2021]. Conversations with friends, family and work colleagues shape inequality perception through experience sharing. The socioeconomic diversity of participants in everyday conversations contributes to reconstructing more accurate images regarding income and wealth inequality than isolated individuals [@summers_deliberating_2022]. Persistent economic inequality led to spatially segregated interactions and isolated lifeworlds that provide meaning to social inequality experiences, resulting in doubts about worthiness when the lower classes contrast themselves with extravagant lifestyles from the upper classes, undermining feelings of social inclusion and cohesion [@sachweh_moral_2012]. Similarly, attachment to society weakens when diversity is undermined by class-homogenous networks, which represents the lack of knowledge about others' lifestyles and experiences [@otero_lives_2022]. These ideas resonate with the concept of 'empathy-gulf', understood as the social distance among groups widened by extreme inequality, increasing the barriers to imagining other's lifestyles and goods, which might diminish feelings of injustice and redistributive demands [@sachweh_moral_2012, p. 19]. Therefore, the life of others become more distant and might have consequences on empathy and solidarity toward others, potentially leading to perceiving fellow citizens as strangers [@otero_lives_2022, p. 758].

Complementary to pure motivational and cognitive processes, attention has increased toward the structural properties of personal networks to explain social perceptual biases. For example, @lee_homophily_2019 demonstrate that according to population group size, minority and majority groups overestimate their size when homophily is high. In contrast, both groups tended to underestimate the size when network diversity was high. However, simulations show that estimation accuracy improves when perceptual biases of individuals and peers are combined, which is more pronounced when homophily is low given the higher exposure to peers with opposing attributes, suggesting this as evidence of social learning and consensus mechanisms (p. 6). Similarly, @schulz_networkbased_2022 modelled the extent to which homophily influences perceived economic inequality. They report that rising economic inequality increases and polarises income-based homophily. Therefore, the discrepancies between actual and perceived inequality may be explained by the increasing distance and selectivity among the middle- and upper-income groups. Suggesting that misperception is not driven purely by cognitive limitations for informational processing; rather, by the limited information set, individuals perform inductively estimate inequality given the available information in their network. Altogether, the studies presented above have contributed to pointing out the relevance of asymmetric homophily in social networks and the mechanisms that might be involved in the formation of perceived economic inequality.

Related survey research should be considered as well. Yet, studies on the relationship between social environment and economic perceptions have been more focused on self-evaluations than perceptions about the distribution of economic resources. For example, in a study on elderly Americans, @bucciol_social_2019 argued that (1) closeness and frequency of contact with friends and family, (2) having access to supportive networks, (2) being socially engaged in organisations, and (4) feelings of community integration tend to enhance perceived social status, particularly among people who are embedded in supportive family and friendship networks and declare higher neighbourhood social cohesion. However, they also found undermining effects of social ties, which are sources of distress and conflict. Similarly, @huang_subjective_2021 suggests that reference groups and social networks embedded in interpersonal relationships boost the perceived status of Australians. Using a social network approach, their study intended to clarify the extent to which social integration and contact processes explain status perception. Their findings suggest that having a reference group, social engagement in organisations, feelings of neighbourhood belonging, and access to resources through social network ties enhanced perceived status. Additionally, @kim_social_2021 studied the consequences of social networks on subjective status in four East Asian countries, arguing that the three social capital dimensions analysed (bonding, cognitive, and bridging) increase perceived status, as well as cross-cultural differences among countries, generating changes in the influence of each dimension. They found that, among the three dimensions, social capital increases perceived status through contact frequency with family and friends (*bonding*), trust towards close ties (*cognitive*), and higher network contacts (*bridging*). However, in individualistic countries such as Japan and Korea, social capital is less relevant than individual status positions, unlike collectivist societies such as China and Taiwan.         

An exploratory study by @joye_measuring_2019 has suggested that individual status position and network resources independently influence people's perception and justification of inequality. On the one hand, perceived and preferred levels of inequality are lower among people with higher economic, cultural and social capital. On the other hand, public support for public welfare policies tends to be higher among people with higher cultural and social resources but is lower for those with higher economic capital (p. 91). This evidence suggests two main remarks: people with higher personal and social resources consider inequality as less problematic and tend to justify it stronger, but other types of capital increase support for public welfare. However, these results need to be scrutinised with attention because they overlooked conceptual distinctions between perceived and preferred inequality combining the same latent factor, which might be correlated but are conceptually different [@Janmaat2013].  

In theory, evidence has suggested that social networks influence perceived economic inequality as well as subjective evaluations of individual status. Regarding the former, it seems that social networks have a virtuous influence on how people perceive themselves and their economic situation, suggesting that social ties perform a supportive welfare function as an expressive outcome of social capital [@lin_building_2001]. Additionally, as a consequence of homophily, social network homogeneity might not have the same influence on social perception, showing that isolated and homogenous environments might influence how people infer the size of groups (e.g. poor) as well as holding biased estimations about their position in the economic distribution, therefore under- or over-estimating their social standing, which might have consequences in their feelings of social integration and well being [@otero_lives_2022;@Olivos-etal2020;@schneider_why_2019]. Yet, evidence in this regard is scarce and requires further inquiries to clarify the claimed influence of network structure on perceived inequality, as well as their interaction with structural factors that might affect their relation (e.g. social class).   

 <!-- - “"thickness" of a relationship (its multiplexity and the frequency of actual contact”  [McPherson et al., 2001, p. 430] me gusta este concepto de thickness / sirve para mostrar la multiplexity \* frecuency 

However, the previous dynamics that lead to inequality perceptions and preferences are often not addressed by the literature.  -->

<!-- idea: if social status increase perceived also general inequality this should increase preferences [@otero_tesis]

idea: if the socioeconomic composition of the personal network increases with status and economic development we should expect that higher occupational composition of the personal networks increase preferences [@otero_tesis]

* Marginalisation and Misperception: Perceiving Gender and Racial Wage Gaps in Ego Networks
https://www.springerprofessional.de/en/marginalisation-and-misperception-perceiving-gender-and-racial-w/19984106
--> 

## Social ties on the demand for redistribution and welfare

As mentioned above, social networks influence people's experience of social life and self-evaluations, as well as the surrounding social and economic conditions. Particularly, it has been shown that social perceptions of economic inequality influence their preferences towards it. However, it is less known about how the composition and resources embedded in social networks influence what people prefer in terms of economic inequality, particularly what are their views regarding the role of government in terms of social policy measures, which in turn are expressed in demands for economic redistribution and social welfare. Despite this, there are some insights in the literature that highlighted the role of social networks on redistributive preferences by describing the impact of civic engagement in voluntary organizations, cross-class embeddedness through kinship and friendship ties, as well as socioeconomic network diversity.    

As mentioned, the literature has previously addressed efforts to address the link between social networks and redistributive preferences. For example, @yamamura_social_2012 argues that community participation boosts contact among low- and high-income groups, increasing demand for redistribution more clearly in high-income people. For them, high social contact might trigger envy from the poorer groups toward the wealthy, arguing that negative externalities, such as greater unhappiness and a rise in crime rate, will motivate altruistic behaviour that increases the willingness of high-income people to redistribute income. They show that higher rates of community participation at the prefecture-level increase support for redistribution in Japan, which is more pronounced for those above the median income of each community. Similarly, the altruistic motivation mechanism has been tested in comparative research, suggesting that the wealthy are more willing to support redistribution when experiencing fear of crime or local crime rates are high [@rueda_who_2019], as well as in contexts with pronounced income inequality [@franetovic_preferences_2022; @dimick_models_2018]. Therefore, it is argued that the rich engage in altruistic support for redistribution to cope with the negative consequences of income inequality.

A body of research has focused on class-based network analysis, particularly on how embeddedness in cross-class relationships influences people's views on redistribution and welfare, allowing the study of attitudinal change from a synthetic scope that entails class material-interests, socio-cultural or normative views, as well as political preferences [@lindh_class_2020]. Hence, the discussion regarding how social class and network segregation intersect for explaining attitudes can be summarised in two mechanisms: (i) social influence and (ii) socialisation processes. 

Employing a nationally representative sample of Swedish citizens, @lindh_missing_2021 scrutinised how social influence and class segregation affect redistributive and social welfare preferences. They argued that people tend to assimilate their opinions and attitudes according to their surrounding peers (*influence*), which is reinforced by the homophilic tendency in tie formation (*segregation*). After accounting by network segregation and current class position, their results suggest that higher contacts in the managerial class negatively impact redistributive demands. In contrast, connections to the working class increase them. Additionally, contact with socio-cultural professionals that entail more inclusive and egalitarian attitudes lowers welfare chauvinism, while it rises with working-class ties that might perceive immigrants as a threat. First, their results account for the independent influence of social networks on redistributive and welfare preferences. Second, provide evidence that attitudes can be strengthened by class homogeneity but can also change through diverse cross-class ties. 

Similarly, recent literature has turned attention to class positions in kinship networks, suggesting that aside from the current class position, additional socialisation sources are cross-class ties through the family of origin and partners. For instance, employing repeated cross-sectional samples of Americans @lee_consider_2023 found class positions of the family of origin shape economic preferences toward redistribution and federal taxes independently of personal class. Similarly, he argues that parental class position is crucial for political socialisation processes during childhood and early adulthood, where class interests and norms are nurtured. The evidence shows that after accounting for the current class position, the family class background has an independent influence on attitudes in line with the class interests, showing that those with parents from the upper classes are less supportive of redistribution, as well as having farming or working-class background hold favourable attitudes. Additionally, a study on European citizens by @paskov_crossclass_2022 goes further and scrutinised to what extent the class positions of parents and partners shape preferences. As mentioned, the family of origin can socialise individuals in early life stages, but other kinship ties are considered as a source of inter-group contact that could influence individuals as well, suggesting that heterogeneity in class ties can reduce negative prejudges toward out groups as contact theory suggests [@pettigrew_intergroup_1998], what in turn might motivate changes in political attitudes [@nathan_context_2023]. They show that kinship class position matters for redistributive preferences, where homogeneity leads to polarised preferences between the upper and working class, but this gradient is blurred as heterogeneity increases. For example, they show that after accounting for current class position, having working (upper) class parents (or partner) decreases (increases) redistributive preferences.  

In addition to kinship ties, friendship ties are important in the formation of attitudes. To this extent, @londono-velez_impact_2022 conducted a study on a sample of affluent Colombian college students suggesting that increasing socioeconomic diversity at the school level introduces changes in friendship ties that have implications for (i) perceived inequality and (ii) support for redistribution. Her argument relies on the assumption that homogeneous networks constitute a limitation for inferences of economic inequality. As a consequence, she posits that being exposed to more socioeconomically heterogeneous reference groups (e.g. friends) might have consequences in redistributive demands via three mechanisms: self-interest, social mobility and distributive justice. On the one hand, the results show that friendship heterogeneity increases the demand for redistribution.  Particularly, contrary to self-interest, exposure to low-income peers improves accuracy in relative income position and poverty rates, increasing high-income students' redistributive preferences. On the other hand, exposure has a null effect on mobility prospects. Finally, it is suggested that contact triggers higher concerns about the fairness of market-based life outcomes for the poor, which motivate higher support for government intervention. Similarly, @beck_explorando_2019 demonstrate that occupational network diversity diminishes justification of unequal access to social services in Chile, suggesting that contact diversity shortens the social distance between low and upper-status groups, providing them with broader images of inequality and the living conditions of others.

<!-- - demanding redistribution can be considered an instrumental action? 

“probable co-evolution of network formation and political attitudes limits the possibility of interpreting cross-sectional associations between network ties and attitudes as exogenous causal effects” [Lindh et al., 2021, p. 699]

- qualitative evidence has shown that higher classes detent stronger meritocratic and lower inequality perceptions what lead them to justify current economic inequality

Percepción de desigualdad "diff income are too large":
https://journals.sagepub.com/doi/full/10.1177/07311214211062106 

- personas de clase servicios perciben menos desigualdad que los de clase trabajadora y media (países de europa)

- “In Chile, income differences are too large.” This measure was conceptualized as tolerance of inequality (Gonthier, 2017; Larsen, 2016; Schröder, 2017). Considering higher scores of this measure have been shown to mean lower tolerance for inequality, we designate said measure as intolerance of inequality.” [@garcia-castro_changing_2022, p. 5] -->

<!-- @schneider_why_2019 subjective social status as a measure of relative deprivation.

Subjective status is a representation, but the imagined top-bottom groups are not clear. Conceptualization about this has to be developed.

“Whether income inequality affects subjective social status by shifting the frames of reference for social comparison towards the upper end of the income stratum and/or by increasing the frequency with which individuals compare themselves to upper-income groups remains unclear.” (Schneider, 2019, p. 17) -->

