---
editor_options:
  markdown:
    wrap: 72
---

# Research plan  

Considering the theoretical and empirical elements presented above, I would like to contribute to the redistributive preference literature and discuss the role of social comparison as a relevant explanatory mechanism. As a result, my main research question is *What is the role of social comparison on redistributive preferences formation?*. In this respect, the first part of my research is to assess the relevance of subjective social status on redistributive preferences from a comparative perspective, considering that individuals' perception of their position in society can be understood as an outcome that derives from the social comparison that is also affected by a contextual characteristic such as objective income inequality at the country level [@Evans2004; @Lindemann2014; @IturraMellado2019].

The second part of my research is based on data from a five-wave panel survey conducted in Chile by the Centre for Social Conflict and Cohesion Studies (2016-2020). This data will allow understanding the role of subjective social status on redistributive preferences from a longitudinal perspective, focusing on how the changes on perceived economic inequality over time could moderate the impact of social comparison outcomes.

Based on the model proposed by @Condon2020, in the third part of my research, I would like to incorporate elements from the distributive justice literature to provide a complete image of the role of reference groups on social comparison and how these factors are associated with redistributive preferences. As @Jasso1990 suggested, the evaluation process is affected by both observer's and observed characteristics, allowing us to estimate how these factors impact a specific outcome. In this respect, on this stage, I will conduct a factorial survey design in Chile and Germany to assess the interplay of the observer characteristic with a set of different vignette characteristics on status perception and redistributive preferences.

\pagebreak

## Preliminary hypothesis

**Reference groups on subjective status**

*Micro*

**Hypothesis:** upward comparison experiences are associated with lower subjective status

**Hypothesis:** higher perceived economic distance from the CEO is associated with lower subjective status

*Macro*

**Hypothesis:** between-country income inequality is associated with lower subjective social status

**Hypothesis:** within-country income inequality is associated with lower subjective social status

**Status on redistributive preferences**

*Micro*

**Hypothesis:** higher subjective social status is associated with higher redistributive preferences. This association will have a higher effect size than objective income.

**Hypothesis:** the negative association of income will be stronger among low subjective status individuals.

*Macro*

**Hypothesis:** higher income inequality decreases the subjective status median and increases preferences for redistribution

*Cross-level*

**Hypothesis:** the association of subjective social status with redistributive preferences will be stronger in contexts of higher income inequality 

**Hypothesis:** among higher subjective and objective status individuals the support for redistribution will be higher for those in context with higher income inequality (objective and subjective altruism)  

